name: Discord Webhook

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "content": "Site has been updated!",
            "embeds": [{
              "title": "New deployment",
              "description": "**${{ github.event.workflow_run.head_commit.message }}**\n\n[🌐 Open Site](https://h6rd.github.io/Dota2PornFxWeb/)",
              "color": 12370112
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}